# Dev tools
brew "apfel"
brew "jq"
brew "gh"
brew "glab"
brew "imagemagick"
brew "ripgrep"
brew "bat"

# Docker
cask "orbstack"

# Databases
cask "tableplus"
cask "sequel-ace"

# Browsers
cask "google-chrome"
cask "firefox"

# Communication
cask "slack"
cask "discord"
cask "signal"
cask "whatsapp"

# Image editors and tools
cask "imageoptim"
cask "ray"

# Utils
cask "android-file-transfer"
cask "appcleaner"
cask "keka"
cask "raycast"
cask "vlc"

# File sharing
tap "localsend/localsend", trusted: { casks: ["localsend"] }
cask "localsend"

# Webcam
cask "ankerwork"
