#!/bin/bash

alias reload="exec $SHELL -l"

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias ..d="cd ~/downloads"
alias ..p="cd ~/projects"

# Directory
alias md="mkdir -p"
alias rd="rmdir"
alias rmf="rm -rf"

# List directory contents
# Always use color output for `ls`
# Detect which `ls` flavor is in use
if ls --color >/dev/null 2>&1; then # GNU `ls`
  LSCOLORFLAG="--color"
else # macOS `ls`
  LSCOLORFLAG="-G"
fi

alias ls="command ls ${LSCOLORFLAG}"

alias ll="ls -lF" # long format
alias la="ls -laF" # long format, including dot files
alias ld="ls -lF | grep '^d'" # Directories
alias l.="ls -ld .*" # Dotfiles

# Edit
alias chmox="chmod +x"

# Get today's date
alias today='date +"%A, %B %-d, %Y, Week: %V"'

# Networking
alias myip='dig @resolver4.opendns.com myip.opendns.com +short' 
alias myip4='dig @resolver4.opendns.com myip.opendns.com +short -4'
alias myip6='dig @resolver1.ipv6-sandbox.opendns.com AAAA myip.opendns.com +short -6'

# Recursively delete `.DS_Store` files
alias dscleanup="find . -name '*.DS_Store' -type f -ls -delete"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# General ssh key
alias copyssh="pbcopy <~/.ssh/id_rsa.pub"
