#!/bin/bash

alias reload="exec $SHELL -l"

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias ..d="cd ~/downloads"
alias ..p="cd ~/projects"

# Directory
alias md="mkdir -p"
alias rd="rmdir"
alias rmf="rm -rf"

# List directory contents
# Always use color output for `ls`
# Detect which `ls` flavor is in use
if ls --color >/dev/null 2>&1; then # GNU `ls`
  LSCOLORFLAG="--color"
else # macOS `ls`
  LSCOLORFLAG="-G"
fi

alias ls="command ls ${LSCOLORFLAG}"

alias ll="ls -lF" # long format
alias la="ls -laF" # long format, including dot files
alias ld="ls -lF | grep '^d'" # Directories
alias l.="ls -ld .*" # Dotfiles

# Edit
alias chmox="chmod +x"

# Get today's date
alias today='date +"%A, %B %-d, %Y, Week: %V"'

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Recursively delete `.DS_Store` files
alias dscleanup="find . -name '*.DS_Store' -type f -ls -delete"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

alias diskspace-report="df -P -kHl"

# Show/hide hidden files in Finder
alias dot-show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias dot-hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias desktop-hide="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias desktop-show="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Networking
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# General ssh key
alias copyssh="pbcopy <~/.ssh/id_rsa.pub"
