#!/bin/bash

# Each alias & function requires it's App or CLI to be installed.

# Brew
alias brewery="brew update && brew upgrade && brew cleanup"

# Browsers
function safari() { open -a Safari "$1"; }
function chrome() { open -a Google\ Chrome "$1"; }
function canary() { open -a Google\ Chrome\ Canary "$1"; }
function firefox() { open -a Firefox "$1"; }
function firefoxDev() { open -a FirefoxDeveloperEdition "$1"; }

# Lighthouse, Always use headless chrome
alias lighthouse='npx lighthouse --chrome-flags="--headless"'

# Artisan
alias art="php artisan"

# Magento
alias m1="magerun"
alias m2="magerun2"
