#!/bin/bash

# Each alias & function requires it's App or CLI to be installed.

# Brew
alias brewery="brew update && brew upgrade && brew cleanup"

# Node
function node-find() {
  find . -name "node_modules" -type d -prune -print | xargs du -chs
}

function node-clean() {
    NODE_MODULES=(`find . -name 'node_modules' -type d -prune`);
    if [[ ${#NODE_MODULES[@]} -eq 0 ]]; then
        echo "No node_modules found to remove";
    else
        echo "Removing:"
        for i in "${NODE_MODULES[@]}"; do
            rm -rf $i
            echo -e "[\033[1;32m✓\033[0m] ${i}"
        done;
    fi
}

# Browsers
function safari() { open -a Safari "$1"; }
function chrome() { open -a Google\ Chrome "$1"; }
function chromebeta() { open -a Google\ Chrome\ Beta "$1"; }
function firefox() { open -a Firefox "$1"; }
function brave() { open -a Brave\ Browser "$1"; }

# Lighthouse, Always use headless chrome
alias lighthouse='command lighthouse --chrome-flags="--headless"'

# Artisan
alias art="php artisan"

# Shopware
# alias sw="bin/console"
function sw() {
  STORE=${2}
  OPEN_CLI="xdg-open" # Linux

  # OSX
  if [[ "$OSTYPE" == "darwin"* ]]; then
    OPEN_CLI="open"
  fi


  case "${@}" in
    "open"*)
      ADMIN_URL="/admin"
      # TODO get url from .env
      URL=$(bin/console system:config:get core.app.shopId.app_url)
      if [[ "$STORE" == "admin" ]]; then
        URL="${URL}${ADMIN_URL}"
        if [[ ! -z $URL ]]; then
          $OPEN_CLI $URL
        fi
      else
        if [[ ! -z $URL ]]; then
          $OPEN_CLI $URL
        fi
      fi
      ;;
    "sample")
      bin/console store:download -p SwagPlatformDemoData
      bin/console plugin:refresh
      bin/console cache:clear
      ;;
    *)
      bin/console $@
      ;;
  esac
}

# Magento
alias m1="magerun"
alias m2="magerun2"
