#!/bin/bash

# Each alias & function requires it's App or CLI to be installed.

# Brew
alias brewery="brew update && brew upgrade && brew cleanup"

# Node
function node-find() {
  find . -name "node_modules" -type d -prune -print | xargs du -chs
}

function node-clean() {
    NODE_MODULES=(`find . -name 'node_modules' -type d -prune`);
    if [[ ${#NODE_MODULES[@]} -eq 0 ]]; then
        echo "No node_modules found to remove";
    else
        echo "Removing:"
        for i in "${NODE_MODULES[@]}"; do
            rm -rf $i
            echo -e "[\033[1;32m✓\033[0m] ${i}"
        done;
    fi
}

# Browsers
function safari() { open -a Safari "$1"; }
function chrome() { open -a Google\ Chrome "$1"; }
function canary() { open -a Google\ Chrome\ Canary "$1"; }
function firefox() { open -a Firefox "$1"; }
function firefoxDev() { open -a FirefoxDeveloperEdition "$1"; }

# Node tools
alias np="command np --any-branch";

# Lighthouse, Always use headless chrome
alias lighthouse='command lighthouse --chrome-flags="--headless"'

# Artisan
alias art="php artisan"

# Composer
alias composer="php -dmemory_limit=-1 `which composer`"

# Magento
alias m1="magerun"
alias m2="magerun2"
