#!/bin/bash

# Set Zed as default code editor
export EDITOR="zed -w"
export VISUAL="zed -w"

# Add local bin
export PATH="$PATH:$HOME/bin"

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1
