#!/bin/bash

# Set VS Code as default code editor
export EDITOR=code

# Add local bin
export PATH="$PATH:$HOME/bin"

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1
