#!/bin/bash

# Navigate up multiple directories
function ..() {
  local times=${1:-1}
  local path=""
  for ((i=0; i<times; i++)); do
    path="../$path"
  done
  cd "$path"
}

# Create a new directory and enter it
function mcd() {
  mkdir -p "$@" && cd "$@"
}

# Find shorthand
function f() {
  find . -name "$1" 2>&1 | grep -v 'Permission denied'
}

# Image conversion: Convert all image files in the current directory to .webp
function to-webp() {
  for PHOTO in *.$1; do
    BASE=$(echo $PHOTO | cut -f 1 -d '.')
    echo $PHOTO $BASE.webp
    convert $PHOTO $BASE.webp
  done
}

# NVM: Auto-switch node version based on .nvmrc
function load-nvmrc() {
  ! command -v nvm &>/dev/null && return

  local nvmrc_path
  nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version
    nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

# Node
function node-find() {
  find . -name "node_modules" -type d -prune -print | xargs du -chs
}

function node-clean() {
  NODE_MODULES=(`find . -name 'node_modules' -type d -prune`);
  if [[ ${#NODE_MODULES[@]} -eq 0 ]]; then
    echo "No node_modules found to remove";
  else
    echo "Removing:"
    for i in "${NODE_MODULES[@]}"; do
      rm -rf $i
      echo -e "[\033[1;32m✓\033[0m] ${i}"
    done;
  fi
}
