#!/bin/bash

# Create a new directory and enter it
function mcd() {
  mkdir -p "$@" && cd "$@"
}

# Find shorthand
function f() {
  find . -name "$1" 2>&1 | grep -v 'Permission denied'
}

# Switch php versions via brew
# NOTE: don't use with Valet plus
function phpuse() {
  brew unlink php@$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
  brew link php@$1 --force
  echo ""
  echo -e "You are now running php@$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")"
}

function to-webp() {
  for PHOTO in *.$1
  do
    BASE=$(echo $PHOTO | cut -f 1 -d '.')
    echo $PHOTO $BASE.webp
	  convert $PHOTO $BASE.webp
  done
}
