# Rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1
  # Mixins
  mixins-before-declarations: 2
  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0
  single-line-per-selector: 0
  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes:
     - 1
     - ignore-non-standard: true
  no-warn: 0
  property-units: 0
  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  # Name Formats
  class-name-format: 1
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1
  # Style Guide
  attribute-quotes: 1
  border-zero:
    - 1
    - convention: '0'
  brace-style:
    - 1
    - style: 1tbs
    - allow-single-line: true
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-args: 1
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  leading-zero:
    - 1
    - include: false
  max-line-length:
    - 1
    - length: 80
    # Unlike to stylelint there is no ignore pattern
    # So url will give an warning
  max-file-line-count:
    - 1
    - length: 300
  indentation: 0
    # indentation is handelt via editorconfig
    # unlike the stylelint, this will also throw an error
    # for multi line properies
  nesting-depth:
    - 2
    - max-depth: 5
  # property-sort-order should be free to the dev to set or maintain
  # It's better to follow the more flexable property type order
  # See Fylgja Style Guide
  property-sort-order: 0
  pseudo-element: 1
  # The string-quotes should be double for CSS
  # But single for Sass specific styles
  quotes: 0
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 2
  # Inner Spacing
  space-after-comma:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-after-bang:
    - 2
    - include: false
  space-between-parens:
    - 1
    - include: false
  space-around-operator: 0
  # Final Items
  trailing-semicolon: 1
  final-newline: 1
